# Macro file for the initialization of SLICS model
# in interactive session
#
# Set some default verbose
#
/control/verbose 2
#/control/saveHistory
/run/verbose 2
/tracking/verbose 1

/geometry/UseTIM_SLICS false


#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute macros/vis.mac
