// © 2026. Triad National Security, LLC. All rights reserved


#include "EventAction.hh"
#include "StackingAction.hh"
#include "G4OpticalPhoton.hh"
#include "G4Track.hh"
#include "G4VProcess.hh"
#include "G4UnitsTable.hh"
#include "G4Electron.hh"
StackingAction::StackingAction(EventAction* eventAction, G4String targetVolumeName)
    : G4UserStackingAction(),
      fEventAction(eventAction),
      fTargetVolumeName(targetVolumeName)
       {}

G4ClassificationOfNewTrack StackingAction::ClassifyNewTrack(const G4Track* aTrack)
{

  G4Track* mutableTrack = const_cast<G4Track*>(aTrack);

  //  Set global time to zero for secondary tracks generated by a very long decay, e.g. products from 207Bi decay.
  //  This part is important for tracking the arrival time of optical photons when a long-lived radioactive source is used.
  const G4VProcess* creator = aTrack->GetCreatorProcess();
  if (creator){
     if(creator->GetProcessName() == "Radioactivation" || mutableTrack->GetGlobalTime()>1E+8) {
       mutableTrack->SetGlobalTime(0.0);
     }
   }


  if (aTrack->GetDefinition()->GetParticleName() == "e-" && aTrack->GetParentID() > 0) {

          G4double energy = aTrack->GetKineticEnergy();

          const G4VProcess* proc = aTrack->GetCreatorProcess();
          if (proc && proc->GetProcessName() == "Radioactivation") {

              fEventAction->GetEmEnergy(energy);

              // Optional energy range filter for Pb-207 CE lines (~500–1000 keV)
              if (energy > 970*CLHEP::keV && energy < 980*CLHEP::keV) {
                fEventAction->Add_IC_beta();
              }
          }
      }



  return fUrgent;
}
